name: Go
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debug
        run: |
          echo "matrix.os: ${{ matrix.os }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref_name: ${{ github.ref_name }}"
          echo "def branch: ${{ github.event.repository.default_branch }}"
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Test with the Go CLI
        run: go test -v ./...
      - name: Report Card
        uses: creekorful/goreportcard-action@v1.0
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
          reuse-go: true
        if: |
          github.event_name == 'push'  &&
          github.ref_name == github.event.repository.default_branch
        continue-on-error: true

