name: Go
on: [push]

permissions:
  contents: write

jobs:
  test-and-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debug
        run: |
          echo "matrix.os: ${{ matrix.os }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref_name: ${{ github.ref_name }}"
          echo "def branch: ${{ github.event.repository.default_branch }}"
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Test with the Go CLI
        run: go test -short -v ./...
      - name: Report Card
        uses: creekorful/goreportcard-action@v1.0
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
          reuse-go: true
        if: |
          github.event_name == 'push'  &&
          github.ref_name == github.event.repository.default_branch
        continue-on-error: true

  make-releases:
    if: github.ref == 'refs/heads/main'
    needs: test-and-stuff
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build release
        run: go build -o aicli-${{ matrix.os }}-${{ matrix.arch }} ./cmd/aicli

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: aicli-${{ matrix.os }}-${{ matrix.arch }}
          path: aicli-${{ matrix.os }}-${{ matrix.arch }}
